export const formOptionObject = {
  monthlyDisabled: false,
  weeklyDisabled: false,
  firstDeliveryDate: 7,
  cycleMonth: [
    { value: 'one_month', label: '1ヶ月ごと' },
    { value: 'two_month', label: '2ヶ月ごと' },
    { value: 'three_month', label: '3ヶ月ごと' },
    { value: 'four_month', label: '4ヶ月ごと' },
    { value: 'five_month', label: '5ヶ月ごと' },
    { value: 'six_month', label: '6ヶ月ごと' },
  ],
  cycleNthWeek: [
    { value: 'per_two_week', label: '2週毎' },
    { value: 'per_three_week', label: '3週毎' },
    { value: 'per_four_week', label: '4週毎' },
  ],
  cycleMonthDayOfWeek: [
    { value: 'sunday', label: '日曜日' },
    { value: 'monday', label: '月曜日' },
    { value: 'tuesday', label: '火曜日' },
    { value: 'wednesday', label: '水曜日' },
    { value: 'thursday', label: '木曜日' },
    { value: 'friday', label: '金曜日' },
    { value: 'saturday', label: '土曜日' },
  ],
  cycleDay: [
    { value: 'day_1', label: '毎月1日' },
    { value: 'day_5', label: '毎月5日' },
    { value: 'day_10', label: '毎月10日' },
    { value: 'day_15', label: '毎月15日' },
    { value: 'day_20', label: '毎月20日' },
    { value: 'day_25', label: '毎月25日' },
    { value: 'end_of_month', label: '毎月月末' },
  ],
  cycleWeek: [
    { value: 'per_two_week', label: '2週毎' },
    { value: 'per_three_week', label: '3週毎' },
    { value: 'per_four_week', label: '4週毎' },
  ],
  cycleWeekDayOfWeek: [
    { value: 'sunday', label: '日曜日' },
    { value: 'monday', label: '月曜日' },
    { value: 'tuesday', label: '火曜日' },
    { value: 'wednesday', label: '水曜日' },
    { value: 'thursday', label: '木曜日' },
    { value: 'friday', label: '金曜日' },
    { value: 'saturday', label: '土曜日' },
  ],
};
